# Generated by Django 2.2.6 on 2019-11-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_auto_20191125_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(upload_to='bg images')),
            ],
        ),
    ]
