# Generated by Django 2.2.6 on 2019-12-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_backgroundimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name_plural': 'About Me',
            },
        ),
    ]
