# Generated by Django 2.2.6 on 2019-12-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0007_auto_20191218_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='title',
            field=models.CharField(default='Python Web Developer And Self Proclaimed Problem Solver.', max_length=200),
            preserve_default=False,
        ),
    ]
